//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinaryStudio.PlatformUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BinaryStudio.PlatformUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error_ConverterFunctionNotDefined.
        /// </summary>
        internal static string Error_ConverterFunctionNotDefined {
            get {
                return ResourceManager.GetString("Error_ConverterFunctionNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error_InsufficientSourceParameters.
        /// </summary>
        internal static string Error_InsufficientSourceParameters {
            get {
                return ResourceManager.GetString("Error_InsufficientSourceParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error_InsufficientTypeParameters.
        /// </summary>
        internal static string Error_InsufficientTypeParameters {
            get {
                return ResourceManager.GetString("Error_InsufficientTypeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error_TargetAtOffsetNotExtendingType.
        /// </summary>
        internal static string Error_TargetAtOffsetNotExtendingType {
            get {
                return ResourceManager.GetString("Error_TargetAtOffsetNotExtendingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error_TargetNotExtendingType.
        /// </summary>
        internal static string Error_TargetNotExtendingType {
            get {
                return ResourceManager.GetString("Error_TargetNotExtendingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error_ValueAtOffsetNotOfType.
        /// </summary>
        internal static string Error_ValueAtOffsetNotOfType {
            get {
                return ResourceManager.GetString("Error_ValueAtOffsetNotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error_ValueNotOfType.
        /// </summary>
        internal static string Error_ValueNotOfType {
            get {
                return ResourceManager.GetString("Error_ValueNotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NormalizeError_InvalidPathChar2.
        /// </summary>
        internal static string NormalizeError_InvalidPathChar {
            get {
                return ResourceManager.GetString("NormalizeError_InvalidPathChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessPriorityClass_AboveNormal.
        /// </summary>
        internal static string ProcessPriorityClass_AboveNormal {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_AboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessPriorityClass_BelowNormal.
        /// </summary>
        internal static string ProcessPriorityClass_BelowNormal {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_BelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessPriorityClass_High.
        /// </summary>
        internal static string ProcessPriorityClass_High {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessPriorityClass_Idle.
        /// </summary>
        internal static string ProcessPriorityClass_Idle {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessPriorityClass_NA.
        /// </summary>
        internal static string ProcessPriorityClass_NA {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessPriorityClass_Normal.
        /// </summary>
        internal static string ProcessPriorityClass_Normal {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessPriorityClass_RealTime.
        /// </summary>
        internal static string ProcessPriorityClass_RealTime {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_RealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services_InvokedOnWrongThread.
        /// </summary>
        internal static string Services_InvokedOnWrongThread {
            get {
                return ResourceManager.GetString("Services_InvokedOnWrongThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThreadHelper_UIThreadDispatcherUnavailable.
        /// </summary>
        internal static string ThreadHelper_UIThreadDispatcherUnavailable {
            get {
                return ResourceManager.GetString("ThreadHelper_UIThreadDispatcherUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateError_GuidEmpty.
        /// </summary>
        internal static string ValidateError_GuidEmpty {
            get {
                return ResourceManager.GetString("ValidateError_GuidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateError_InvalidOperation.
        /// </summary>
        internal static string ValidateError_InvalidOperation {
            get {
                return ResourceManager.GetString("ValidateError_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateError_InvalidValue_Format.
        /// </summary>
        internal static string ValidateError_InvalidValue_Format {
            get {
                return ResourceManager.GetString("ValidateError_InvalidValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateError_OutOfRange_Format.
        /// </summary>
        internal static string ValidateError_OutOfRange_Format {
            get {
                return ResourceManager.GetString("ValidateError_OutOfRange_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateError_PathNotNormalized_Format.
        /// </summary>
        internal static string ValidateError_PathNotNormalized_Format {
            get {
                return ResourceManager.GetString("ValidateError_PathNotNormalized_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateError_StringEmpty.
        /// </summary>
        internal static string ValidateError_StringEmpty {
            get {
                return ResourceManager.GetString("ValidateError_StringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateError_StringWhiteSpace.
        /// </summary>
        internal static string ValidateError_StringWhiteSpace {
            get {
                return ResourceManager.GetString("ValidateError_StringWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateError_UnexpectedValue_Format.
        /// </summary>
        internal static string ValidateError_UnexpectedValue_Format {
            get {
                return ResourceManager.GetString("ValidateError_UnexpectedValue_Format", resourceCulture);
            }
        }
    }
}
